### ISSUE TITLE
add title to image

### ISSUE THREAD

**Issue by sarangan** [brh55/react-native-masonry#19]
is there anyway we can add captions for images? thanks

**Comment by brh55** [comment]
Hey @sarangan ,
Currently no way to add captions for images, is there a particular layout you want the captions you are trying to accomplished? Maybe we can see if we can implement something you are looking for.

**Comment by sarangan** [comment]
Hi, thanks a lot for your reply. I was trying to achieve like Pinterest kinda layout images with captions, then I thought it would be out of scope. this component works great compare to other components out there. i can inject Text components inside the Column.js when rendering the Image in that way i can alter the layout. you are the best. thank you again. keep rocking bro.

**Comment by sarangan** [comment]
Hi one more question, does this mansory component affect performance compare to regular Images load from url?

**Comment by brh55** [comment]
@sarangan It's using [Image.getSize](https://facebook.github.io/react-native/docs/image.html) under the hood. Naturally the performance overhead is downloading the image -> caching it -> displaying it on screen with correct sizing. I would assume the overhead is very much similar to using `<Image>` with resize set to cover.

**Comment by brh55** [comment]
Also appreciate the kind words 🤘 , you keep on rocking too!

**Comment by sarangan** [comment]
Thanks bro 👍
