### ISSUE TITLE
Is there any way to render a custom component instead an image?

### ISSUE THREAD

**Issue by cinder92** [brh55/react-native-masonry#20]
Hello i just say this plugin only accept images, is there any way to implemente custom components?

**Comment by brh55** [comment]
Hey @cinder92 , currently there isn't a way to implement custom components. If your components don't have images, nested within, then it's easily accomplishable using a combination of `width %` and `justify-contents: space-in-between`. When you add images into the remote pictures into the equation it's a little difficult.

**Comment by cinder92** [comment]
its a combination of text with remote images, i just tried to edit your plugin, but its a little bit difficult

**Comment by brh55** [comment]
@cinder92 , Yeah that is rather difficult, and something I haven't come up with a solution for yet. You could try a combination of a parent view (acting as a container)  and `resizeMode` set to cover or contain on the image.

Unfortunately, I would need to investigate a little further and experiment. If you do come up with a working implementation, we can road map that into this project. 💃

**Comment by brh55** [comment]
Going to close for now.

**Comment by brh55** [comment]
@cinder92 Currently have a working implementation on the ability to render footer and header components on branch `render-footer-header`. But it's not fully tested yet, and I need to do some reorganization for prop checking, however, I expect sometime next week I'll have it done and stable.

<img width="186" alt="screen shot 2017-05-26 at 8 14 13 am" src="https://cloud.githubusercontent.com/assets/6020066/26500594/54a26fce-41eb-11e7-9e56-ac3e3d8197c0.png">

**Comment by brh55** [comment]
Merged into master

**Comment by cinder92** [comment]
thanks a lot! i will test it!
