### ISSUE TITLE
Simplified example renders nothing

### ISSUE THREAD

**Issue by fxfactorial** [brh55/react-native-masonry#27]
I have a suspicion you are assuming existence of the header/footer as your example builds/runs but when I try my simplified code I get nothing rendered. 

```

const onPress = e => console.log(e);
const img1 = 'https://img.buzzfeed.com/buzzfeed-static/static/2014-12/1/15/enhanced/webdr02/enhanced-18393-1417466529-5.jpg';
const img2 = 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXXTmdaGSOFK8iBeYqoA6_XiQGGWvu6KGnqAxXYyvJA-JKin8ImQ';
const img3 = 'https://img.buzzfeed.com/buzzfeed-static/static/2015-04/3/15/enhanced/webdr06/enhanced-24427-1428089292-2.jpg';

// And tried with flex: 1, I know container is coming up on UI, but no images. 
...render

      <View style={{height: '100%'}}>
        <Masonry
          columns={3}
          bricks={[
            { uri: img1, id: 1, onPress },
            { uri: img2, id: 2, onPress },
            { uri: img3 , id: 3, onPress}
          ]}
          />
      </View>
```

**Comment by brh55** [comment]
Odd it will display if you wrap the masonry with a scrollview. I'm assuming it has to do with the listview.rowHasChanged method.

![image](https://user-images.githubusercontent.com/6020066/27399594-e9e47ebe-5682-11e7-9633-3f72a5267a0e.png)

```
import React, { Component } from 'react';
import {
	ScrollView
} from 'react-native';
import Masonry from 'react-native-masonry';

const onPress = e => console.log(e);
const img1 = 'https://img.buzzfeed.com/buzzfeed-static/static/2014-12/1/15/enhanced/webdr02/enhanced-18393-1417466529-5.jpg';
const img2 = 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXXTmdaGSOFK8iBeYqoA6_XiQGGWvu6KGnqAxXYyvJA-JKin8ImQ';
const img3 = 'https://img.buzzfeed.com/buzzfeed-static/static/2015-04/3/15/enhanced/webdr06/enhanced-24427-1428089292-2.jpg';


export default class example extends Component {
  constructor() {
    super();
  }

  render() {
    return (
      <ScrollView style={{backgroundColor: '#f4f4f4'}}>
        <Masonry
          columns={3}
          bricks={[
            { uri: img1, id: 1, onPress },
            { uri: img2, id: 2, onPress },
            { uri: img3 , id: 3, onPress}
          ]}
          />
      </ScrollView>
    );
  }
}
```

**Comment by fxfactorial** [comment]
@brh55 Masonry isn't a ScrollView already? I would say it should be right?

**Comment by brh55** [comment]
@fxfactorial going to take a bit of time as not familiar with FlatList but will try to give it a whirl

**Comment by fxfactorial** [comment]
@brh55 its a simplified API, easier to work with. 

Thanks for quick replies :)

**Comment by brh55** [comment]
@fxfactorial No problem, thanks for the reports! Will need to get back to work unfortunately lol.

**Comment by fxfactorial** [comment]
@brh55 also, I'm noticing that some times images render and sometimes they don't. Not sure if somehow related RNM.

**Comment by brh55** [comment]
Hmm any console warnings? RNM will let you know if it failed to load the image, and it will skip the brick entirely.

**Comment by fxfactorial** [comment]
No, none, would have mentioned it.

**Comment by brh55** [comment]
Let me see if I can try to reproduce the issue, do you have the image urls?

**Comment by fxfactorial** [comment]
ya, same ones I was using in that original example

**Comment by fxfactorial** [comment]
@brh55 
![indeterminate](https://user-images.githubusercontent.com/3036816/27406254-323e6520-5689-11e7-8025-238186ecf0e9.gif)

**Comment by brh55** [comment]
Hmm... looks to be with the listview. Looks like listview is rendering the first row with an empty set of images, but not refreshing it's state when the images are fetched.

**Comment by fxfactorial** [comment]
all the more reason to move to FlatList :)

**Comment by brh55** [comment]
@fxfactorial Haha it can't be avoided I suppose

**Comment by srameshr** [comment]
@brh55 +1 for the FlatList. ListView as it stands is intimidating. Also the images are not rendered in order. How about images should compulsory render according the the image id or any other key from left to right?
