### ISSUE TITLE
Migrate to FlatList

### ISSUE THREAD

**Issue by brh55** [brh55/react-native-masonry#28]
As title explains, I will try to get to this when I have time  (3 - 4 weeks), but open for grabs as well.

**Comment by fxfactorial** [comment]
Would need to bump up a min requirement, which I think is fine to do in this fast moving environment.

**Comment by brh55** [comment]
Shouldn't be **too** bad.

**Comment by srameshr** [comment]
Is this done? ListView is daunting.

**Comment by brh55** [comment]
@srameshr Per docs masonry layouts *(different heights)* are not supported, so if I went with a flatlist + numColumns approach. Judging by the rendered outcomes as it appears a <view> wraps each element in a horizontal row, and proceeds to stack additional wrapped views.

**Comment by srameshr** [comment]
@brh55 Agreed.

**Comment by brh55** [comment]
Tied to #33 . Currently in review.
