### ISSUE TITLE
Add TouchableHighlight Support

### ISSUE THREAD

**Issue by brh55** [brh55/react-native-masonry#3]
- If user provides a `props.onPress`, the image should invoke the props onPress function with the object in the data array

**Comment by brh55** [comment]
Merged with #6

**Comment by neo125874** [comment]
@brh55 hi, didn't figure out how to put the onPress method? and if the data array could add other attribute? like: `[{uri: 'xxx.jpg', id: 'db-id-xxx'}, {uri: 'yyy.jpg', id: 'db-id-yyy'}, ...]`
then, get the custom attribute(id) from the onPress method?

thanks

**Comment by brh55** [comment]
@neo125874 Hey your on press would look like this:
```
{
    uri: 'xxx.jpg',
    id: 'db-id-xxx',
    onPress: (data) => { 
         console.log(data.id) // db-id-xxx
    }
}
```

**Comment by neo125874** [comment]
@brh55 thanks for your answering, could i set the press method one time? or i have to set every object a key-attribute?

**Comment by brh55** [comment]
You would need to set it every time. As you most likely know, I would recommend setting function as a variable like such:
```
const brickHandler = (data) => console.log(data.id);

...
[
{
    uri: 'xxx.jpg',
    id: 'db-id-xxx',
    onPress: brickHandler
},
{
    uri: 'yyy.jpg',
    id: 'db-id-yyy',
    onPress: brickHandler
}
]
```
