### ISSUE TITLE
The order in which images are rendered is not ordered

### ISSUE THREAD

**Issue by srameshr** [brh55/react-native-masonry#30]
Here is the screenshot: [https://ibb.co/eEVsFF](https://ibb.co/eEVsFF)
```
const data = [
  {
    id: 3,
    uri: 'https://image.shutterstock.com/z/stock-photo-collage-of-happy-family-resting-at-home-103862393.jpg'
  },
  {
    id: 1,
    uri: 'https://s-media-cache-ak0.pinimg.com/736x/01/c0/1c/01c01c45cb997f16675c5a5825645ceb.jpg'
  },
  {
    id: 2,
    uri: 'https://i.ytimg.com/vi/tYBk4kLHPkk/maxresdefault.jpg'
  },

];
```

If this is the data, images are rendered in a single column.

Also the images are not ordered according to the array of data source.

**Comment by brh55** [comment]
Currently they are pushed into the columns as soon as they are rendered, hence why things may be out of order, but this could be fixed. Going to label as bug.

**Comment by srameshr** [comment]
@brh55 Nice to hear that! It happens on images of particular size. If I add this image [https://image.shutterstock.com/z/stock-photo-collage-of-happy-family-resting-at-home-103862393.jpg](https://image.shutterstock.com/z/stock-photo-collage-of-happy-family-resting-at-home-103862393.jpg) at the first position in the array to the existing app, it renders at the end.

Images should be rendered according the their position in the array, right?

**Comment by brh55** [comment]
Indeed, that would most likely be the expected outcome. You are more than welcome to tackle this in a PR :), you would just need to adjust a few lines in the image resolve function to "insert" into the columns oppose to pushing to top of the list. 

Sorry, I would do this, but been a bit busy with life / and some what code burnt lately.

**Comment by srameshr** [comment]
@brh55 I totally understand! I will give it a try.

**Comment by brh55** [comment]
Pretty much! 🤓

**Comment by kmcgill88** [comment]
I'm interested in this functionality and am looking forward to 0.3.0. I can try get it done if you're looking for help.

**Comment by brh55** [comment]
@kmcgill88 You should def try to tackle this! Looking for additional maintainers, as I'm not currently using RN-Masonry for my current project, just maintaining it on the side.

**Comment by kmcgill88** [comment]
@brh55 I'm actually taking a crack at it right now. I'm new to react-native so I'm struggling my way through.
