### ISSUE TITLE
Load image not show 

### ISSUE THREAD

**Issue by tuananhdtu** [brh55/react-native-masonry#35]
When the first load screen, masonry load image for two column.
But the second and the 3th, masonry load image for left column or right colum

![0-sa-d2-75dad76b98f466399a91fc9d7411d81a](https://user-images.githubusercontent.com/2296411/29955220-60c2d9f0-8f08-11e7-8a3f-e631ab393e6a.jpg)
![0-sa-d3-35c05dd610a524aa08d0e22ee11b9b36](https://user-images.githubusercontent.com/2296411/29955221-61dd8bf0-8f08-11e7-81a0-e81a1b25860c.jpg)

**Comment by brh55** [comment]
Do you have code sample?

**Comment by wassgha** [comment]
Having the same problem! A dirty fix is to refresh the component after images have been loaded (I do it by settings columns to `this.state.column` and calling `setState({column: 2})` after a timeout). Please fix :)

**Comment by vvavepacket** [comment]
@wassgha im also experiencing same issue and trying your dirty fix.  what is the initial value of your this.state.column? did u set an initial state? i tried setting it initially as 1 (screen showed 1 column,) and then after some time delay, it rerendered now showing 2 columns... not the behavior i wanted(user can see columns changing from 1 to 2).. :(

**Comment by wassgha** [comment]
@vvavepacket that is what I have right now except probably with a smaller delay (I have 1 second). In my case, it might have helped that the images I'm loading are remote so when the state is set to one row the images probably haven't loaded yet so I can't see them.

**Comment by brh55** [comment]
`v0.4.4` should resolve these issues now, also update react-navigation.

**Comment by mohsaadi** [comment]
@brh55 
I have the same issue using latest version v0.5.0-alpha.1. 
I've noticed when setState({column: }) is called with the current column number, i.e. calling it twice with same value, after the second call, the images will disappear.

**Comment by brh55** [comment]
@mohsaadi let's open a new issue for this, need more context and code to explain the issue

**Comment by mohsaadi** [comment]
Thanks Brandon,
Here's a video https://drive.google.com/open?id=1mr-4Nodl1cpJbGq1uQuonEq_9DaWHp2a that shows the behavior described in my previous comment. I did nothing but replaced the "App.js" of a new react-native project with the app.js provided by the masonry's example here: "https://github.com/brh55/react-native-masonry/tree/master/example".
