### ISSUE TITLE
Column widths not updated after rotation

### ISSUE THREAD

**Issue by kmcgill88** [brh55/react-native-masonry#42]
To reproduce:
1. Start app and rotate from portrait to landscape
2. one column will not be updated while in landscape
3. Rotate back to portrait and things are fine.

If you are in landscape and toggle a different column size and toggle back to the original size of 2 and continue to rotate things appear to be fine.

I need this functionality and will work on it.

![simulator screen shot sep 3 2017 9 14 55 pm](https://user-images.githubusercontent.com/1992370/30233957-cb6290aa-94be-11e7-98b5-4da75d0af069.png)
![simulator screen shot sep 3 2017 9 06 39 pm](https://user-images.githubusercontent.com/1992370/30233958-cb73fd54-94be-11e7-9bfd-3412ef5c7b1d.png)

**Comment by srameshr** [comment]
@kmcgill88 How do I contact you?
