### ISSUE TITLE
Add advance usage examples in Readme

### ISSUE THREAD

**Issue by brh55** [brh55/react-native-masonry#44]
For v0.4.0 the custom image component is for advance usage, and should include additional examples.

Pull into branch v0.4.0

**Comment by srameshr** [comment]
@brh55 Could you please merge FlatList and  custom image component into the main branch?

**Comment by brh55** [comment]
I was looking into consolidating everything yesterday and replacing the `ListView`. Definitely some issues still with using `FlatList` as a parent wrapper, so I've put that into it's own experimental branch for now. I'll look into doing a bit more testing tonight, and merge in.

**Comment by kmcgill88** [comment]
Sounds like a good plan!

**Comment by srameshr** [comment]
@brh55 Eagerly waiting! I desperately need pull to refresh for now.

**Comment by brh55** [comment]
@srameshr you can test out the existing branch by pulling the repository into a directory link it (`npm link`). Then in your project symlink it with  `npm link react-native-masonry`.
