### ISSUE TITLE
Add props to define priority arrangement

### ISSUE THREAD

**Issue by brh55** [brh55/react-native-masonry#5]
An API could look something like such:
### `props.priority` or `props.arrangement`:
- `order` / `ascending` - **Default**: Placement occurs in sequence (1, 2, 3)
- `vertical` - Looks at which column has the least vertical height, and position "brick" within that column
- `reverse` / `descending` - reverse placement in column (3, 2, 1)

**Comment by srameshr** [comment]
@brh55 Is this in progress?

**Comment by brh55** [comment]
Not currently, some of these options do require a bit of work to develop. Open for grabs.

**Comment by srameshr** [comment]
@brh55 Its not ordering by default as of now.
