### ISSUE TITLE
when i using customImageComponent(FastImage) just show border 'red'

### ISSUE THREAD

**Issue by zanisis** [brh55/react-native-masonry#50]
My ScreenShoot
<img width="313" alt="screen shot 2017-09-20 at 6 24 29 am" src="https://user-images.githubusercontent.com/25142795/30620001-f1678bc2-9dcc-11e7-94d7-b06faea6a90b.png">

My Code
`<View style={{flex: 1, flexGrow: 10, marginTop: 4}}>
     <Masonry
       sorted
       bricks={this.state.originImg}
       columns={this.state.columns}
       customImageComponent={FastImage}
       customImageProps={FastImage} />     
</View>`

**Comment by brh55** [comment]
Did you install FastImage and run `$npm link react-native-fast-image`? Afterwards, you need to restart the bundler

**Comment by zanisis** [comment]
already using react-native link

my package.json
```
"react": "16.0.0-alpha.12",
"react-native": "0.45.1",
"react-native-fast-image": "^1.0.0",
"react-native-masonry": "^0.4.0",
"react-native-svg": "5.2.0"
```

my code
```
export default class SVG extends Component { render() {
    return (
      <View style={styles.container}>
        <Masonry
          sorted
          column={2}
          bricks={[
            { uri: 'https://i.pinimg.com/736x/a4/b2/98/a4b298e715660b8e5b9402d21276fb88--shoes-platform-sneakers-suede-puma-shoes.jpg' },
            { uri: 'https://i.pinimg.com/736x/63/bf/51/63bf51af7b5e322329af89d795962fe0--nike-knit-shoes-tennis-shoes-womens-nike-running.jpg' },
            { uri: 'http://4.bp.blogspot.com/-wMj-artgutU/VjFZE_fuo-I/AAAAAAAAcdU/W0pluz-4Yn0/s1600/2015%2B1028%2BNike%2BFree%2B5.0%2BTR%2BFit%2B5%2BMetallic%2BBlack%253ABlue%2BLagoon%253AGlacier%2BBlue%253AMetallic%2BSilver%2B%2B.png' },
            { uri: 'https://s.aolcdn.com/hss/storage/midas/1c38860b2eafca9d23de549e74b15286/204650181/nikehyperadaptlede.jpg'},
            { uri: 'https://i.pinimg.com/736x/cf/cc/bb/cfccbbe0784bdd37084aa6ee709c31b4--mens-sneakers-fashion-sneakers-mens.jpg'}
          ]}
          customImageComponent={FastImage}
        />
      </View>
    );
  }}
```

**Comment by brh55** [comment]
@zanisis I would recommend recompiling the project, since FastImage is a native-dep module. `$ react-native run-ios`

**Comment by zanisis** [comment]
i try running on ios maybe on android not supported but on ios is still same only show border red not showing image

**Comment by brh55** [comment]
Please run without `customImageComponent` and tell me if it renders properly

**Comment by brh55** [comment]
Closing issue, hopefully it should be working now 👯‍♂️
