### ISSUE TITLE
making images show rounded corners

### ISSUE THREAD

**Issue by vvavepacket** [brh55/react-native-masonry#54]
Where is the best way in this library to make images have rounded corners?

[https://imgur.com/a/xEoKs](https://imgur.com/a/xEoKs)

**Comment by brh55** [comment]
@vvavepacket You should be able to add border radius properties to `imageContainerStyle`

**Comment by brh55** [comment]
@vvavepacket has this been solved?

**Comment by vvavepacket** [comment]
@brh55  i added the border radius properties but it is not taking effect on Android.. Other people have this worked on iOS, but not android. Have u tried the same on Android? Thank you.

**Comment by vvavepacket** [comment]
@brh55   Can we reopen the issue? Thank you.
