### ISSUE TITLE
Layout Issues When Dynamically Adding Data

### ISSUE THREAD

**Issue by brh55** [brh55/react-native-masonry#61]
As @srameshr pointed out, there is issues when the data is added. 

This probably has to do with `masonry.js` willReceiveNextProps and how masonry does some internal caching to prevent re-resolving bricks. Will need to investigate and figure out what the issue is.

**Comment by srameshr** [comment]
I cross verified it and its working on ```0.4.4``` of masonry.

**Comment by brh55** [comment]
@srameshr ! Glad this solves it! 👯‍♂️
