### ISSUE TITLE
When i refesh  but it not show view 

### ISSUE THREAD

**Issue by nguyenquangtrung** [brh55/react-native-masonry#66]
When I run react-native run-android view show colum left and right .but when i click R +R refesh It just show view column Left or column right not show together

**Comment by brh55** [comment]
@nguyenquangtrung what version are you on?

**Comment by nguyenquangtrung** [comment]
I use react-native 0.49
"dependencies": {
		"data.task": "^3.1.1",
		"lodash.differenceby": "^4.8.0",
		"lodash.isequal": "^4.5.0",
		"opencollective": "^1.0.3",
		"prop-types": "^15.5.8",
		"react-native-injectable-component": "^0.1.2",
		"react": "16.0.0",
		"react-native": "0.50.3",
		"react-native-masonry": "^0.4.4",
		"react-native-vector-icons": "^4.4.2"
	},
	"peerDependencies": {
		"react": "*",
		"react-native": "^0.43.0"
	},
	"devDependencies": {
		"babel-jest": "21.2.0",
		"babel-preset-react-native": "4.0.0",
		"jest": "21.2.1",
		"react-test-renderer": "16.0.0"
	},

**Comment by brh55** [comment]
@nguyenquangtrung Can you add screenshot and code  (or is this example?)

**Comment by nguyenquangtrung** [comment]
yes,when I run react-native run-android it as image
​and when i click R+R refesh it as image
​Please see your help!

2017-11-15 1:11 GMT+07:00 Brandon Him <notifications@github.com>:

**Comment by brh55** [comment]
Please pull v0.4.5 and let me know if this fixes that issue. It's most likely implementation details that may be wrong.
