### ISSUE TITLE
Adding onPress support for header and footer

### ISSUE THREAD

**Issue by mohammedpascal** [brh55/react-native-masonry#68]
Hi, thanks for the awesome component!

I am working on a project and I want to be able to press on footer as well, but when I add onPress to the footer doesn't work for some reason, can you please help?

**Comment by brh55** [comment]
@mohammedpascal 
Hmm I don't see why it wouldn't work considering the footer and headers render verbatim, what is your existing mark up?

**Comment by brh55** [comment]
@mohammedpascal hopefully you figured this out, will close :)
