### ISSUE TITLE
Can this render video?

### ISSUE THREAD

**Issue by Lesliesibbs** [brh55/react-native-masonry#69]
i wanted to load videos form server and was wondering if the layout would be able to handle it?

**Comment by brh55** [comment]
Hey @Lesliesibbs 

Currently react-native-masonry does not allow video, it would be interesting to do a fork to allow this.

However, I may consider stripping the logic into it's own core module, which would let devs create their own layouts with provided width constraints passed to their renderer, while keeping this for convenience purposes. But unsure if this is what people are looking though.

**Comment by Lesliesibbs** [comment]
i certainly would welcome it as a core module and a quick google search on this topic suggests others might be interested too (https://www.youtube.com/watch?v=JxnVjobYTJQ) views alone would suggest.
