### ISSUE TITLE
Add Header/Footer component for the list.

### ISSUE THREAD

**Issue by margox** [brh55/react-native-masonry#79]
Is there any way to add a header or footer for the list? not for the image item. just like the ListHeaderComponent/ListFooterComponent prop of FlatList component.

**Comment by brh55** [comment]
@margox Not currently, but it would not be too hard to implement. How would you imagine the prop to look like for passing this into the masonry?

**Comment by peterchibunna** [comment]
I think it'd be nice if we can have a prop of the masonry (e.g., renderHeader, renderFooter) which is passed directly to the Masonry component which would take each item as parameter and then could return a view which is positioned on top/at below, the same way you have the footer and header but just that the prop needs to be direct to the Masonry component. If you can guide us on how to do that, it'll be awesome.

**Comment by peterchibunna** [comment]
I think it'd be nice if we can have a prop of the masonry (e.g., renderHeader, renderFooter) which is passed directly to the Masonry component which would take each item as parameter and then could return a view which is positioned on top/at below, the same way you have the footer and header but just that the prop needs to be direct to the Masonry component. If you can guide us on how to do that, it'll be awesome.

**Comment by brh55** [comment]
Are you referring to the top and bottom of the masonry layout itself? @peterchibunna

**Comment by QuentinBrosse** [comment]
@brh55 What do you think about the implementation of FlatList with `ListFooterComponent` and `ListHeaderComponent ? https://facebook.github.io/react-native/docs/flatlist#listfootercomponent

**Comment by brh55** [comment]
@QuentinBrosse Rather an odd use-case as each column is a `FlatList`, but I can understand if a user wants to generate a column header of some sort. 

...However, the API would need to be pretty simple to correlate with the number of desired columns, or we if we are assuming users want to render a particular view dynamic column, we can pass some metadata passed into the render function (like column number, counts, etc).

What kind of use-case are we trying to accomplish?

**Comment by skizzo** [comment]
Is it somehow possible to achieve what [`FlatList`](https://reactnative.dev/docs/flatlist) does with [`ListHeaderComponent`](https://reactnative.dev/docs/flatlist#listheadercomponent) and [`ListFooterComponent`](https://reactnative.dev/docs/flatlist#listfootercomponent) in 2022? If not, in my case this is a huge dealbreaker for using this otherwise great component.

**Comment by brh55** [comment]
Sorry, I haven't been really coding for quite some time. But given how much time has past, I'm sure there are some other great alternatives open-source modules out there. Happy to take any adaptions using these new components, I doubt it will be a serious lift.

I have plans on getting back into a development, once I find a company / position that brings me closer to coding again.
