### ISSUE TITLE
Place Header/Footer on the Image, not above and beneath.

### ISSUE THREAD

**Issue by kevinscience** [brh55/react-native-masonry#80]
Love react-native-masonry? Please consider supporting our collective:
👉  https://opencollective.com/react-native-masonry/donate 

Is there a way to place the Header/Footer on the image? It would be more stylish. Thank you!
![snapchatdiscover](https://user-images.githubusercontent.com/19722517/37551144-972b54ce-2970-11e8-8ab6-f048a48184e4.png)

**Comment by kevinscience** [comment]
Actually, I got it. By setting position of header/footer to 'absolute'.

**Comment by brh55** [comment]
@kevinscience Yes that would be purely style driven, using position absolute would be the best way to go about this.

**Comment by abhinav011085** [comment]
@kevinscience how did you set the position of the footer to 'absolute'??

**Comment by brh55** [comment]
@abhinav011085 It's used the same way in traditional CSS, I would suggest reading many articles on how to use `position: absolute`, but you would set `relative` to parent, then `absolute` on element (footer or header), then adjust `top` or `bottom` properties.
