### ISSUE TITLE
Only one row appearing on iPhone X

### ISSUE THREAD

**Issue by mzgnr** [brh55/react-native-masonry#85]
## Possible Implementation

Only one row appearing on iPhone X

**Comment by lc3t35** [comment]
![capture d ecran 2018-06-04 a 14 03 08](https://user-images.githubusercontent.com/921372/40916459-172b7884-6800-11e8-8d6f-0fc6ab737cd7.png)

I have this too along with https://github.com/brh55/react-native-masonry/issues/81.
react-native@0.55.2 (expo sdk 27), react@16.3.1
